### ISSUE TITLE
Snakebite unable to parse core-site.xml in EMR 

### ISSUE THREAD

**Issue by karthich** [spotify/snakebite#113]
When snakebite attempts to read core-site.xml file on EMR, it is looking for the property name 'fs.defaultFS' for the name of the master node. But in EMR clusters, that property is under the name 'fs.default.name'. To accomodate this, config.py should attempt to search for this value name if the first value search returns null.

Excerpt from the core-site.xml file from EMR:
```
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<configuration>
  <property><name>hadoop.proxyuser.hadoop.groups</name><value>*</value></property>
  <property><name>fs.s3n.impl</name><value>com.amazon.ws.emr.hadoop.fs.EmrFileSystem</value></property>
  <property><name>fs.s3.impl</name><value>com.amazon.ws.emr.hadoop.fs.EmrFileSystem</value></property>
  <property><name>fs.default.name</name><value>masterNodeName</value></property>....
```

**Comment by ravwojdyla** [comment]
closed via #114
