### ISSUE TITLE
copyToLocal trying to write to / regardless of dst

### ISSUE THREAD

**Issue by esseye** [spotify/snakebite#134]
Given a list of source files like so
['/rawdata/date_id=20150127/datacenter_id=CHCM/file.dat',
 '/rawdata/date_id=20150127/datacenter_id=CHCM/file2.dat',
 '/rawdata/date_id=20150127/datacenter_id=CHCM/file3.dat',
 '/rawdata/date_id=20150127/datacenter_id=CHCM/file4.dat',
 '/rawdata/date_id=20150127/datacenter_id=CHCM/file5.dat']

and an output dir like so
'/data/CHCM_20150127/files'

copyToLocal(source, dst) is trying to write the returned files to root "/"

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/grab/lib/python2.7/site-packages/grab/grab.py", line 274, in getFromHDFS
    for i in hdfsGetter(fileList, self.myDataDirectory, webhdfs = self.webhdfs, nodelist = self.nodelist, server = self.server):
  File "/opt/grab/lib/python2.7/site-packages/grab/grab.py", line 110, in hdfsGetter
    for i in myhandle.copyToLocal(filelist, mylocalpath + '/'):
  File "/opt/grab/lib/python2.7/site-packages/snakebite/client.py", line 1398, in wrapped
    yield results.next()
  File "/opt/grab/lib/python2.7/site-packages/snakebite/client.py", line 704, in copyToLocal
    for item in self._find_items(paths, processor, include_toplevel=True, recurse=True, include_children=True):
  File "/opt/grab/lib/python2.7/site-packages/snakebite/client.py", line 1167, in _find_items
    entry = processor(full_path, fileinfo.fs)
  File "/opt/grab/lib/python2.7/site-packages/snakebite/client.py", line 703, in <lambda>
    processor = lambda path, node, dst=dst, check_crc=check_crc: self._handle_copyToLocal(path, node, dst, check_crc)
  File "/opt/grab/lib/python2.7/site-packages/snakebite/client.py", line 738, in _handle_copyToLocal
    f = open(temporary_target, 'w')
IOError: [Errno 13] Permission denied: '/file.dat'

**Comment by ravwojdyla** [comment]
This problem happens is destination is a directory, `copyToLocal` works fine if destination is not a directory. This problem was introduced by #132.

**Comment by epogrelis** [comment]
The problem is caused by the way self.base_source in client.py is being determined. It's splitting the full path such that the last element (the filename) gets the slash, rather than the slash being on the end of self.base_source. os.path.join drops all components in the join prior to an absolute path if it encounters one, which is what's breaking. We've been working around it internally by making the following edit in client.py: 

def_handle_copyToLocal(self, path, node, dst, check_crc):
        # Calculate base directory using the first node only
        if self.base_source is None:
            self.dst = os.path.abspath(dst)
            if os.path.isdir(dst):  # If input destination is an existing directory, include toplevel
                **self.base_source = os.path.dirname(path)**
            else:
                self.base_source = path
 
To this: 
 
def_handle_copyToLocal(self, path, node, dst, check_crc):
        # Calculate base directory using the first node only
        if self.base_source is None:
            self.dst = os.path.abspath(dst)
            if os.path.isdir(dst):  # If input destination is an existing directory, include toplevel
                **self.base_source = os.path.dirname(path) + "/"**
            else:
                self.base_source = path

**Comment by ravwojdyla** [comment]
@epogrelis exactly :+1: would you like to provide PR with fix/test-case?
