### ISSUE TITLE
Support fully qualified URIs

### ISSUE THREAD

**Issue by jkukul** [spotify/snakebite#146]
Currently fully qualified HDFS URIs are not supported. E.g:
```
client.ls(['hdfs://nnAddress:nnPort/path'])
```
will result in `org.apache.hadoop.fs.InvalidPathException`, because normalizations that happen [here](https://github.com/spotify/snakebite/blob/master/snakebite/client.py#L1147) and [here](https://github.com/spotify/snakebite/blob/master/snakebite/client.py#L1151) will produce an invalid path like this:
```
/user/someuser/hdfs:/nnAddress:nnPort/path
```

Two seemingly straight-forward solutions to enhance current state would be to:
1. detect fully qualified path early on and throw a more obvious `not supported exception`
2. detect fully qualified path early on and remove the prefix so that **snakebite** can carry on as usual

**Comment by ravwojdyla** [comment]
@jkukul thanks for filing issue!

That is the case because in snakebite there's assumption that clients are created per HDFS cluster (HA enabled or not) thus developer provides addresses/ports in CTOR of snakebite client.

Is this assumption a blocker or problem in some case, could you elaborate?

**Comment by jkukul** [comment]
@ravwojdyla 
I totally agree with the assumption that `clients are created per HDFS cluster (HA enabled or not)`. My issue relates to a situation when a developer passes a full URI of the same cluster for which the client is configured.

**Comment by wouterdebie** [comment]
I'm not sure we want to stimulate this behavior. I think it's the responsibility of the developer to make sure that the input is sanitized. Having snakebite respond to URIs in those calls makes it do magic under the hood. Basically if client.host+client.port are in the URI, snakebite should work, but otherwise it shouldn't. Magic :)
