### ISSUE TITLE
"test" command fails if the file name contains hdfs:// prefix

### ISSUE THREAD

**Issue by neutronsharc** [spotify/snakebite#148]
Hi the team,

I ran the following test cmd and it failed.  The test cmd succeeds if I don't include "hdfs://namenode:port" prefix in the file name.  However, "ls" cmd works fine with hdfs:// prefix.

===================
snakebite -D -n hdfsbackup-namenode001 -p 8020 test hdfs://hdfsbackup-namenode001:8020/user/shawn/compare-dir-0.1.jar
DEBUG:snakebite.client:Trying to find path /user/shawn/hdfs://hdfsbackup-namenode001:8020/user/shawn/compare-dir-0.1.jar
DEBUG:snakebite.channel:RequestContext (len: 57):

userInfo {
  effectiveUser: "shawn"
}
protocol: "org.apache.hadoop.hdfs.protocol.ClientProtocol"

DEBUG:snakebite.channel:############## CONNECTING ##############
DEBUG:snakebite.channel:RpcPayloadHeader (len: 6):

rpcKind: RPC_PROTOCOL_BUFFER
rpcOp: RPC_FINAL_PAYLOAD
callId: 0

DEBUG:snakebite.channel:Protobuf message:

src: "/user/shawn/hdfs://hdfsbackup-namenode001:8020/user/shawn/compare-dir-0.1.jar"

DEBUG:snakebite.channel:Protobuf message bytes (79): 0a 4d 2f 75 73 65 72 2f 73 68 61 77 6e 2f 68 64 66 73 3a 2f 2f 68 64 66 73 62 61 63 6b 75 70 2d 6e 61 6d 65 6e 6f 64 65 30 30 31 3a 38 30 32 30 2f 75 73 65 72 2f 73 68 61 77 6e 2f 63 6f 6d 70 61 72 65 2d 64 69 72 2d 30 2e 31 2e 6a 61 72
DEBUG:snakebite.channel:RpcRequest (len: 144):

methodName: "getFileInfo"
request: "\nM/user/shawn/hdfs://hdfsbackup-namenode001:8020/user/shawn/compare-dir-0.1.jar"
declaringClassProtocolName: "org.apache.hadoop.hdfs.protocol.ClientProtocol"
clientProtocolVersion: 1

DEBUG:snakebite.channel:############## SENDING ##############
DEBUG:snakebite.channel:Header + payload len: 153
DEBUG:snakebite.channel:############## RECVING ##############
DEBUG:snakebite.channel:############## PARSING ##############
DEBUG:snakebite.channel:Payload class: <class 'snakebite.protobuf.ClientNamenodeProtocol_pb2.GetFileInfoResponseProto'>
DEBUG:snakebite.channel:Bytes read: 8, total: 8
DEBUG:snakebite.channel:Rewinding pos 7 with 8 places
DEBUG:snakebite.channel:Reset buffer to pos -1
DEBUG:snakebite.channel:---- Parsing header ----
DEBUG:snakebite.channel:Delimited message length (pos 1): 4
DEBUG:snakebite.channel:Rewinding pos 3 with 3 places
DEBUG:snakebite.channel:Reset buffer to pos 0
DEBUG:snakebite.channel:Delimited message bytes (4): 08 00 10 01
DEBUG:snakebite.channel:Response header:

callId: 0
status: ERROR

DEBUG:snakebite.channel:Bytes read: 1, total: 9
DEBUG:snakebite.channel:4 bytes delimited part length: 41
DEBUG:snakebite.channel:Class name length: 41
DEBUG:snakebite.channel:Bytes read: 41, total: 50
DEBUG:snakebite.channel:Class name (41): org.apache.hadoop.fs.InvalidPathException
DEBUG:snakebite.channel:Bytes read: 4, total: 54
DEBUG:snakebite.channel:4 bytes delimited part length: 1174
DEBUG:snakebite.channel:Stack trace length: 1174
DEBUG:snakebite.channel:Bytes read: 1174, total: 1228
DEBUG:snakebite.channel:Stack trace (1174): Invalid path name Invalid file name: /user/shawn/hdfs://hdfsbackup-namenode001:8020/user/shawn/compare-dir-0.1.jar
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:2881)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:674)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:643)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java:44128)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:453)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1002)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1695)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1691)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:396)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1408)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:1689)

DEBUG:snakebite.channel:Invalid path name Invalid file name: /user/shawn/hdfs://hdfsbackup-namenode001:8020/user/shawn/compare-dir-0.1.jar
Request error: Invalid path name Invalid file name: /user/shawn/hdfs://hdfsbackup-namenode001:8020/user/shawn/compare-dir-0.1.jar

**Comment by ravwojdyla** [comment]
hi @neutronsharc !

Thanks for filing the issue and using snakebite!

This is indeed an issue, sorry about that - will take a look at it.
