### ISSUE TITLE
Provide message in Exception raised from Client._read_file

### ISSUE THREAD

**Issue by ghedsouza** [spotify/snakebite#154]
This exception:

https://github.com/spotify/snakebite/blob/a0a928f07603f0494366844949a4b666e8e256c2/snakebite/client.py#L1114

should provide a message describing in some detail what went wrong. Was hitting this Exception when the data node was unreachable.

**Comment by Tarrasch** [comment]
We will appreciate it if you send PR for this please.

**Comment by Tarrasch** [comment]
@ravwojdyla, you should fix the general build errors, see https://github.com/spotify/luigi/commit/14819e885d30c024e6778013534a2411e0f9d035

**Comment by ghedsouza** [comment]
Fix merged: https://github.com/spotify/snakebite/pull/155
