### ISSUE TITLE
HADOOP_HOME is deprecated.

### ISSUE THREAD

**Issue by simar7** [spotify/snakebite#161]
Hello!

I was trying out snakebite on my hadoop cluster and it seems that snakebite still uses HADOOP_HOME environment variable to check things. To my knowledge, this had been deprecated lately and most new users will not have this in their config files.

I can write a patch and submit a PR that can fix this to check on HADOOP_INSTALL or HADOOP_PREFIX (both in most cases point to the same path, usually /usr/local/hadoop)

**Comment by wouterdebie** [comment]
Would be great if you write a patch (+tests) for this!

**Comment by ehiggs** [comment]
[HADOOP_HOME is no longer deprecated.](https://issues.apache.org/jira/browse/HADOOP-11393).

**Comment by simar7** [comment]
Thanks for pointing that out @ehiggs
