### ISSUE TITLE
Library not compatible with Windows

### ISSUE THREAD

**Issue by pragmattica** [spotify/snakebite#162]
I'm using Python 2.7.10 on Windows 7. I installed snakebite using the version of Pip that's bundled with the Python 2.7 Windows installer (ie. `pip install snakebite`).

When I then try to make use of snakebite as an HDFS client, I get a stack trace on import:
```
C:\Python27>python
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from snakebite.client import HAClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\snakebite\client.py", line 19, in <module>
    from snakebite.service import RpcService
  File "C:\Python27\lib\site-packages\snakebite\service.py", line 16, in <module>
    from snakebite.channel import SocketRpcChannel
  File "C:\Python27\lib\site-packages\snakebite\channel.py", line 44, in <module>
    import pwd
ImportError: No module named pwd
```

I may be doing something obviously wrong here, so my apologies if this isn't a real issue. If this is a known problem, I'd be interested in trying to put together a pull request to fix it. Thanks!

**Comment by wouterdebie** [comment]
I think the pwd module is only available for Unix systems. We use this to get the username that runs snakebite. I have no idea  how this works in Windows. I'll leave this issue open to see if I can find a solution. 
Yay for platform independence :S

// Wouter

Fatfingered on an iPhone
