### ISSUE TITLE
Kerberos principal hardwired

### ISSUE THREAD

**Issue by sbretzel** [spotify/snakebite#167]
Hello,
we have faced issues connecting to our Hadoop cluster with snakebite. Finally, we found out that in snakebite the name node's kerberos principal is hardwired to be "hdfs" -- see the connect()-method in snakebite.rpc_sasl.SaslRpcClient, where the attribute "service" is set to "hdfs". Changing "hdfs" to the name of our kerberos principal resolved our issues.

The way it looks to me is that snakebite only evaluates hdfs-site.xml in order to obtain the name node's address and port and to find out if the cluster runs in secure mode by checking whether the property hadoop.security.authentication has the value "kerberos". I guess the way it "should" be is that the kerberos principal configured by the property dfs.namenode.kerberos.principal 
should be used to set the kerberos principal rather than hardwiring it to "hdfs". In other words, the kerberos principal's name obtained from that setting should be passed to snakebite.rpc_sasl.SaslRpcClient and used in its connect()-method to set the attribute "service" accordingly.

Best regards,
Stefan

**Comment by bolkedebruin** [comment]
You are most likely right. I'll check your assumption and create a pull request next week or maybe this weekend.

**Comment by bolkedebruin** [comment]
@sbretzel can you check and close the issue if it is fixed?

**Comment by sbretzel** [comment]
Hi,
I've tested the most recent snakebite release (2.7.2) and it works like a charm. So I guess this issue can be considered resolved.
Thanks & best regards,
Stefan
