### ISSUE TITLE
Cannot find krb5.h, enusre you have installed krb5 development library.

### ISSUE THREAD

**Issue by tungwaiyip** [spotify/snakebite#168]
I hit a krb5.h error when pip install. It looks like there is a hard dependency on the python-krbV library. Is this absolutely required for snakebite to work? In the spotify blog post, it advertises itself as a a pure Python HDFS client.

Anyway, I commented out any references to sasl and kerberos. Snakebite seems to work this way.

**Comment by wouterdebie** [comment]
Snakebite itself is pure python but relies on other packages, which imho is fine. Not sure what to do about the dependencies of the python-krbV library though. My pip foo isn't that great, but maybe @ravwojdyla can help out.

**Comment by wouterdebie** [comment]
Also, we currently rely on python-prototobuf  which is a C package as well.

**Comment by wouterdebie** [comment]
This does create a problem however. I'm running into this issue when building the docs.

**Comment by wouterdebie** [comment]
I've pushed a PR that should address this:

https://github.com/spotify/snakebite/pull/170

**Comment by tungwaiyip** [comment]
Wonderful! Can you post to pypi?

**Comment by tungwaiyip** [comment]
One workaround until 2.7.0 is uploaded is to use

   pip install snakebite==2.5.5

**Comment by wouterdebie** [comment]
Done!
