### ISSUE TITLE
Exception: RpcBufferedReader only managed to read 0 out of 4 bytes

### ISSUE THREAD

**Issue by praveev** [spotify/snakebite#169]
I am running hadoop-2.6.0 locally on my mac and have snakebite version 2.6.1.

When I invoke `snakebite -n 127.0.0.1 -p 50010 ls / ` from the CLI, I receive this exception.

I also copied the example from here http://spotify.github.io/snakebite/client.html:

` from snakebite.client import Client `
` client = Client("localhost", 50010, use_trash=False) `
` for x in client.ls(['/']): `
`	print x`

I have a test folder in the root. The exception I get is **Exception: RpcBufferedReader only managed to read 0 out of 4 bytes**

The README says snakebite 2.x supports Hadoop 2.2.0 and up. My namenode is 127.0.0.1:50010 and I have localhost pointing to 127.0.0.1. I've tried with both localhost and 127.0.0.1.

Do you know why this would happen?

**Comment by wouterdebie** [comment]
Do you seen anything in your namenode logs? The error seems to be generated on the server side.
At Spotify we run snakebite against Hadoop 2.6.0, so I'm not sure if the Hadoop version is the issue.
Do other operations work?

**Comment by wouterdebie** [comment]
And are you sure 50010 is the HDFS port and not the HTTP one?

**Comment by praveev** [comment]
@wouterdebie thanks. I was indeed using the HTTP port and not HDFS one.
