### ISSUE TITLE
NameError: global name 'SaslRpcClient' is not defined

### ISSUE THREAD

**Issue by praveev** [spotify/snakebite#174]
I see this error when I simply do `snakebite -D ls /`. I have rpc_sasl.py where SaslRpcClient is defined. 
Do you know why this is happening?

**Comment by praveev** [comment]
There seems to be an issue with the conditional import in channel.py.

@bolkedebruin helped identify this issue: https://github.com/airbnb/airflow/pull/438

If you add:
from snakebite.rpc_sasl import SaslRpcClien
from snakebite.kerberos import Kerberos

to the top of snakebite/channel.py it should start working

**Comment by bolkedebruin** [comment]
To make it a bit clearer this is when using kerberos. The conditional import that happens in channel.init(...) seems not to be persistent when a call to get_connection happens.

I'm not sure how to fix this.

**Comment by praveev** [comment]
my bad. I rushed the explanation. much better.
