### ISSUE TITLE
List requirements for Client.{ls,cat,text}

### ISSUE THREAD

**Issue by obalaspiq** [spotify/snakebite#181]
Is there a reason these methods require a list? Or maybe better question, is there a reason not to add `if isinstance(paths, str): paths = [paths]` so that paths can either be a single directory/file or a list of directories/files?

**Comment by wouterdebie** [comment]
No particular reason, but I think we wanted a consistent interface and not have magic happen in the implementation. Let the user take care of transforming arguments into lists. The api itself now makes it clear that those operations can operate on multiple paths at the same time.
