### ISSUE TITLE
No copyFromLocal function in CLI client command line

### ISSUE THREAD

**Issue by qianglchina** [spotify/snakebite#183]
Hi,
I have checked the usage of command line. There is only "copyToLocal"  and I can't  find "copyFromLocal". 

how should i do if i want to put local file to hdfs by this client ?

**Comment by crorella** [comment]
They disabled that option in 2.2, not sure why.

**Comment by wouterdebie** [comment]
The option was there, but it was never implemented and was confusing.

Duplicate of #37
