### ISSUE TITLE
Snakebite calling wrong python directory

### ISSUE THREAD

**Issue by fjblau** [spotify/snakebite#186]
Franks-MacBook-Pro:bin frankblau$ snakebite -version
-bash: /usr/local/bin/snakebite: /usr/local/opt/python/bin/python2.7: bad interpreter: No such file or directory

How do I tell snakebite where python is?

**Comment by wouterdebie** [comment]
Seems there is a problem with your setup. Snakebite uses `/usr/bin/env python` to figure out where your python is. Does the command `python` work for you?
