### ISSUE TITLE
IWBN to retry after namenode failures

### ISSUE THREAD

**Issue by jcdecho** [spotify/snakebite#191]
Hello,
When snakebite queries all known namenode servers, and they fail, we get errors like:

INFO:  File "... /snakebite/client.py", line 1392, in wrapped
INFO:    self.__handle_request_error(e)
INFO:  File " ... /snakebite/client.py", line 1370, in __handle_request_error
INFO:    self.namenode.next()
INFO:  File " ... /snakebite/client.py", line 1361, in _switch_namenode
INFO:    raise OutOfNNException(msg)
INFO:OutOfNNException: Request tried and failed for all 2 namenodes:
INFO:                  * ...-namenode-...
INFO:                  * ...-namenode-....

It would be great if snakebite could retry after errors like this, instead of failing.  One possibility would be to exponentially increase retry times, up to some limit of retries or time.

Thank you,
- Jim

**Comment by wouterdebie** [comment]
Sounds sensible we should have retry logic. Some thoughts:

- I think this should be configurable by the user (max retries, retry length, exponential back-off, etc) and we shouldn't change snakebites default behavior (= no retry).
- When do we retry? Only on OutOfNNException will only work for the HAClient. Are there other cases where we want to retry? Like ConnectionRefused, etc?

**Comment by wouterdebie** [comment]
#194 should help with this. Feedback before we merge this would be appreciated!

**Comment by wouterdebie** [comment]
#194 fixes this.
