### ISSUE TITLE
no module named Client

### ISSUE THREAD

**Issue by austintrombley** [spotify/snakebite#197]
When I tried this code from the documentation:

from snakebite.client import Client

I got the following error:
>>> from snakebite.client import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named client

**Comment by wouterdebie** [comment]
Are you sure snakebite is in your python path?

**Comment by austintrombley** [comment]
I did a pip uninstall and then easy_install of snakebite and it worked
