### ISSUE TITLE
can not put file to hdfs

### ISSUE THREAD

**Issue by francisar** [spotify/snakebite#211]
this client doesn't support put file to hdfs

**Comment by guhehehe** [comment]
there's a [thread for this feature](https://github.com/spotify/snakebite/issues/37) long time ago, but somehow it's never implemented.

**Comment by wouterdebie** [comment]
Yep, duplicate of #37

**Comment by francisar** [comment]
wait for it

**Comment by lixiang2017** [comment]
wait for it
