### ISSUE TITLE
SyntaxError: invalid syntax -- baseTime = min(time * (1L << retries), cap);

### ISSUE THREAD

**Issue by ulf1** [spotify/snakebite#250]
python 3.6.2

importing 
```
from snakebite.client import Client
```

results in
```
  File "<input>", line 1, in <module>
    from snakebite.client import Client
  File "/***********/lib/python3.6/site-packages/snakebite/client.py", line 1473
    baseTime = min(time * (1L << retries), cap);
                            ^
SyntaxError: invalid syntax
```

It is the same issue as in https://github.com/spotify/snakebite/issues/216

Providing a Python 3 package is misleading, and should be removed from pypi if does not work.

**Comment by parsatorb** [comment]
Just ran into this as well :(

**Comment by fifar** [comment]
Just ran into this as well :(
Please fix it, thanks.

**Comment by rationalbeing** [comment]
this is not fixed! someone remove it or solve the issue

**Comment by OOPMan** [comment]
@rationalbeing @fifar The author of this library no longer works at Spotify and Spotify no longer use this library. See https://github.com/spotify/snakebite/issues/62

At this point, Spotify do not care enough to even close this ticket. Could people please stop adding comments to this ticket. Instead, head over to https://pypi.org/project/snakebite-py3/ and get the version that works on Python 3

**Comment by ulf1** [comment]
Thanks OOPMan.
I closing this issue for this dead repo.

**Comment by IslemAtimi** [comment]
la solution est simple:
pip install snakebite-py3
ou
pip3 install snakebite-py3
