### ISSUE TITLE
broken pipe

### ISSUE THREAD

**Issue by BlondAngel** [spotify/snakebite#39]
I installed it using 'pip install snakebite'  onto the Cloudera Demo VM (http://www.cloudera.com/content/support/en/downloads/download-components/download-products.html)

And I get a 'broken pipe' error.  Any suggestions on how to fix it?

Reference:
'snakebite -D ls /'
DEBUG:snakebite.client:Trying to find path / DEBUG:snakebite.channel:############## CONNECTING ##############
DEBUG:snakebite.channel:Sending: 68 72 70 63 (len: 4)
DEBUG:snakebite.channel:Sending: 09 (len: 1)
DEBUG:snakebite.channel:Sending: 00 (len: 1)
DEBUG:snakebite.channel:Sending: 00 (len: 1) DEBUG:snakebite.channel:RpcRequestHeaderProto (len: 26):

rpcKind: RPC_PROTOCOL_BUFFER
rpcOp: RPC_FINAL_PACKET
callId: -3
clientId: "aad60a7f-0a44-4d"
retryCount: -1

DEBUG:snakebite.channel:RequestContext (len: 60):

userInfo {
  realUser: "cloudera"
}
protocol: "org.apache.hadoop.hdfs.protocol.ClientProtocol"

DEBUG:snakebite.channel:Header length: 88 (00 00 00 58 (len: 4))
DEBUG:snakebite.channel:Sending: 00 00 00 58 (len: 4)
DEBUG:snakebite.channel:Sending: 1a (len: 1) DEBUG:snakebite.channel:Closing socket Traceback (most recent call last):
  File "/usr/bin/snakebite", line 39, in <module>
    SnakebiteCli()
  File "/usr/bin/snakebite", line 30, in **init**
    clparser.execute()
  File "/usr/lib/python2.6/site-packages/snakebite/commandlineparser.py", line 340, in execute
    exitError(e)
  File "/usr/lib/python2.6/site-packages/snakebite/commandlineparser.py", line 46, in exitError
    raise error
socket.error: [Errno 32] Broken pipe

**Comment by jackyao** [comment]
2017-08-07 15:47:37,862 WARN org.apache.hadoop.ipc.Server: Incorrect header or version mismatch from 10.4.37.222:35721 got version 9 expected version 4
