### ISSUE TITLE
Unexpected end-group tag.

### ISSUE THREAD

**Issue by bung87** [spotify/snakebite#99]
/root/portal/lib/python2.7/site-packages/google/protobuf/internal/python_message.pyc in MergeFromString(self, serialized)
    842         # The only reason _InternalParse would return early is if it
    843         # encountered an end-group tag.
--> 844         raise message_mod.DecodeError('Unexpected end-group tag.')
    845     except (IndexError, TypeError):
    846       # Now ord(buf[p:p+1]) == ord('') gets TypeError.

**Comment by bung87** [comment]
Hi @ravwojdyla,
python version 2.7 is correct.it has been a while,as you described above,I think I may not install protobufers successfully.since I try to use https://github.com/mtth/hdfs and it works fine,Thank you and happy new year!

**Comment by ravwojdyla** [comment]
Hi @bung87  - thanks for update. Closing for now - if this happens again, please let us know.
Happy new year!

**Comment by ispmarin** [comment]
Hey all,

Sorry about going back to a closed issue but I'm having the same message when trying to connect to my hadoop cluster. 

- protobuf 2.6.1, python 2.7
- snakebite 2.7.2

Any hints?

Cheers
